// [v1475] LE CA DU TABLEAU DE BORD RESTAIT FIGÉ. Ben : « quand je vais dans l'onglet année le CA de l'année en cours n'évolue pas malgré les commandes soldées ». Le MOTEUR était sain (vérifié : 725 € pour 3 paiements + 1 marché sur 2026, somme des mois = année). Le défaut était le CACHE du graphique, vidé uniquement par un rendu complet de l'accueil : ① changer d'onglet relisait le cache au lieu de recharger → chiffres figés à toutes les granularités ; ② l'accueil reste monté pendant qu'on saisit ailleurs → au retour, chiffres d'avant la saisie. FIX : changer d'onglet recharge ; toute écriture d'argent invalide le cache (4 points de paiement, sauvegarde de commande, clôture de marché). Le 4e point a été trouvé PAR LE TEST, pas par l'inspection manuelle. Suite v1475 : 18 assertions, sensibilité vérifiée par réintroduction (2 rouges).
// [v1474] AUDIT 2e PASSE : 4 écritures de perte dont l'échec était invisible. L'erreur partait dans la console et le flux continuait — message de succès affiché, écran fermé. Gravité liée à l'ORDRE : casse en production (stock décrémenté juste avant), perte matière (lot supprimé juste après), casse au scan et écart au picking (toast « Stock mis à jour » quoi qu'il arrive). Les quatre préviennent et interrompent désormais ; le lot matière n'est supprimé qu'après une écriture réussie. Les écritures accessoires (audit, calendrier) et celles protégées par une transaction gardent leur silence — c'est correct. Autres familles vérifiées et saines : 2586 fonctions sans doublon, aucun await perdu dans un forEach, aucun NaN/Infinity ne peut atteindre l'écran. Suite v1474 : 16 assertions, garde de motif ayant trouvé 2 défauts de plus que l'inspection manuelle.
// [v1473] AUDIT : 15 TABLES N'ÉTAIENT PAS SAUVEGARDÉES. La sauvegarde parcourait 31 tables sur 46 — stockMoves (traçabilité des mouvements de stock), journalCompta, materialLosses, tout l'espace R&D, la communication et le plan de production étaient perdus SILENCIEUSEMENT à la restauration sur appareil vierge. backups et errLog restent volontairement exclus. PARADE INDISPENSABLE : la restauration vide chaque table avant de la remplir — une ancienne sauvegarde aurait donc EFFACÉ ces tables. La règle v1372 (kv/auditLog) est généralisée : une table absente du fichier est INCONNUE, pas vide, et reste intacte ; un tableau vide reste une mesure et vide bien la table. Les sauvegardes existantes restent valides (somme de contrôle calculée sur le périmètre inscrit dans le fichier). Suite v1473 : 27 assertions, sensibilité vérifiée par réintroduction (4 rouges).
// [v1472] CORRIGER LES HORAIRES D'UNE SESSION D'ATELIER. Ben : « fermer une session laissée ouverte pendant un temps démesurément grand ». La clôture fixait toujours la fin à MAINTENANT : une session oubliée la nuit enregistrait 14 h d'atelier, temps qui alimente le temps par recette, donc la rentabilité par parfum et le coût de revient. Bouton « Horaires » sur chaque session du journal (ouverte ou clôturée) : début et fin saisissables, fin vide = session ouverte. Heures en heure LOCALE, pas UTC. GARDE : les tâches sont ramenées dans les nouvelles bornes (tâche jamais arrêtée clôturée avec la session, tâche débordante rognée, pause soldée à la fin retenue) — sinon le temps par recette dépasserait la session qui le contient. Fin antérieure au début refusée. Suite v1472 : 26 assertions, réconciliation « toutes les tâches tiennent dans la session », sensibilité vérifiée par mutation (5 rouges).
// [v1471] PICKING GROUPÉ PAR DATE + LE SCAN PERMET ENFIN D'AGIR. Picking groupé : commandes regroupées par DATE DE LIVRAISON EXACTE, une section par date, seule la plus proche pré-cochée (avant : « checked » en dur partout, aucun regroupement). Bouton coche/décoche par vague. Commande sans macaron grisée et signalée au lieu de disparaître à l'étape suivante. SCAN : le scan aboutissait sur la fiche de TRAÇABILITÉ (consultation). La fonction d'affectation existait mais n'était atteignable que depuis une fiche production, jamais depuis un scan. Le scan ouvre maintenant un ÉCRAN D'ACTIONS : servir une commande, emporter en marché, retirer une quantité, consulter la traçabilité. Boîte vide ou composant non vendable signalé explicitement. Ajout : sortie marché DU LOT SCANNÉ (le moteur existant puise en FIFO sur le parfum — l'inverse du geste de scanner une boîte précise). Mêmes écritures que lui, sans le choix du lot. Suite v1471 : 38 assertions, réconciliation stock/marché, sensibilité vérifiée par réintroduction (7 rouges).
// [v1470] IMPOSSIBLE D'AJOUTER UN NOUVEAU CLIENT. Ben : « c'est un bug que je n'avais pas avant ». Le bouton « + Nouveau client » appelait clientFiche() (la fiche intelligente) SANS identifiant : celle-ci convertit son argument en nombre, obtient NaN, ne trouve aucun client, affiche « Client introuvable » et s'arrête. Régression introduite quand la fiche intelligente a remplacé l'ancien écran — le bouton d'AJOUT a suivi la nouvelle fonction au lieu de rester sur le FORMULAIRE DE CRÉATION, seul capable de fonctionner sans client existant. FIX : le bouton repointe vers le formulaire de création. GARDE-FOU : appelée sans identifiant valide, la fiche intelligente redirige vers la création au lieu d'un cul-de-sac, sans même interroger la base. Suite v1470 : 29 assertions, sensibilité vérifiée par réintroduction du bug exact.
// [v1469] AFFICHÉ ≠ FACTURÉ, ET SACHET REMIS AU LINÉAIRE. 1) Une ligne EN COURS DE SAISIE était tarifée comme une ligne HÉRITÉE : le sachet annonçait 6,50 € et « Montant ligne » facturait 7,50 €. L'absence de marqueur signifie « ligne héritée → grille historique » — juste pour une ligne enregistrée, faux pour une ligne en cours de saisie. Résolveur distinct (tarifsLigneSaisie) pour le modèle d'édition ; les lignes enregistrées gardent l'autre. Vrac et grand format avaient la même faille. 2) Les prix affichés de la personnalisation étaient FIGÉS à 0,25 € en 3 endroits alors que le calcul appliquait 0,30 € : le total était juste mais l'écran mentait. 3) Sachet : Ben a tranché, 2,50 €/macaron dans tous les cas (3 pièces = 7,50 €), donc pas dégressif et insensible à la case. Suite v1463 : 111 assertions, sensibilité vérifiée par réintroduction des défauts exacts.
// [v1468] LES OPTIONS SUIVAIENT ENCORE LA DATE, PAS LA CASE. Ben : « la mise à jour de +0,30cts pour la personnalisation des couleurs n'est pas passé. Quoi que je coche ça reste à 25cts ». En v1466 la tarification des LIGNES est passée sur la case, mais les options de niveau COMMANDE (perso couleurs, logo, forfait création) sont restées sur l'ancienne règle par date — en août elles retombaient donc sur la grille historique, insensibles à la case. FIX : même règle partout. Ces options prennent un CONTEXTE (commande, ou formulaire en cours) au lieu d'une date. Commande héritée sans marqueur → grille historique : aucune facture émise ne bouge. Marqueur de tarif désormais posé au niveau commande aussi. Suite v1463 : 98 assertions, sensibilité vérifiée par réintroduction du défaut exact (0,30 € attendu, 0,25 € obtenu).
// [v1467] LE SÉLECTEUR AFFICHAIT LE PRIX DU CATALOGUE, PAS CELUI APPLIQUÉ. Capture de Ben : bandeau « tarifs en vigueur », case décochée, et la liste proposait « Coffret 6 macarons — 12,00 € ». La liste déroulante des tailles construisait ses libellés avec la valeur brute du catalogue produits, sans passer par coffretUnitPrice (seule fonction qui connaît la grille et la case). Le prix facturé était correct depuis la v1465 : c'est l'affichage qui mentait — pire, puisque Ben choisit sur ce qu'il lit. FIX : chaque option affiche le prix réellement appliqué, case comprise. AJOUT : le catalogue produits est aligné sur la grille au démarrage (il gardait les prix d'installation), de façon PRUDENTE — un prix personnalisé n'est jamais écrasé, les tailles sur mesure restent intactes. Suite v1463 : 85 assertions, sensibilité vérifiée par réintroduction du défaut exact (4 rouges).
// [v1466] LA CASE DÉCIDE, PLUS LA DATE. Ben : « une commande, peu importe sa date de saisie, doit pouvoir afficher les nouveaux prix si la case anciens tarifs est décochée ». La déduction par la date est abandonnée comme règle de tarification (elle empêchait de saisir dès août une commande aux nouveaux tarifs). Décochée = tarifs en vigueur quelle que soit la date ; cochée = anciens tarifs. CE QUI PROTÈGE ENCORE L'HISTORIQUE : une ligne enregistrée avant la v1463 n'a ni drapeau ni marque de tarif — cette absence sert de marqueur d'ancienneté et lui applique la grille historique. Aucune facture émise ne bouge ; les coffrets restent doublement protégés (prix scellé). Bandeau et libellé de la case réécrits (ils décrivaient encore l'antidatation, comportement qui n'existe plus). Suite v1463 : 77 assertions, sensibilité vérifiée par mutation réelle.
// [v1465] CORRECTIF : les nouveaux tarifs COFFRETS ne s'appliquaient pas en saisie. Une ligne en cours de saisie n'a pas encore sa marque de tarif (posée à l'enregistrement) → l'ordre de priorité la faisait retomber sur le CATALOGUE produits (prix d'installation 12/16/22/28/42 €). Une commande datée de septembre affichait 12 € pour un coffret de 6 au lieu de 14 €, et ce prix faux était SCELLÉ à l'enregistrement. L'ordre posé en v1463 protégeait le passé mais pas le chemin d'une saisie neuve. FIX : la grille datée prime sur le catalogue même sans marque de tarif ; le catalogue n'est plus qu'un repli pour les tailles hors grille. Sachets, événements, vrac pro et gros macarons n'étaient pas touchés (pas de catalogue). Suite v1463 étendue : 75 assertions, scénario chiffré exact (14 € et non 12 €), sensibilité vérifiée par réintroduction (3 rouges).
// [v1464] CASE « ANCIENS TARIFS » + GROS MACARONS. Ben : « au pire tu ajoutes une case à cocher ancien tarifs. Si c'est coché alors tous les sélecteurs affichent l'ancien tarif. » Résout le cas qu'une date seule ne couvrait pas (commande prise avant le 01/09 mais livrée après — l'app ne stocke que la date de livraison). Le choix explicite PRIME sur la déduction par la date ; le drapeau est copié sur chaque ligne et conservé à la réouverture ; le bandeau l'annonce. Gros macarons ajoutés à la grille datée : 7 € grand public, 3,80 € pro (anciens prix conservés avant le 01/09). Le 2e argument de bigPrice est optionnel — les appels d'affichage existants restent valides. Suite v1463 étendue : 67 assertions, sensibilité vérifiée par mutation réelle (4 rouges).
// [v1463] NOUVELLE GRILLE TARIFAIRE AU 01/09/2026 + VERROU ANTI-DATATION. Seuls les coffrets scellaient leur prix ; événement, vrac pro, sachet, pyramide et personnalisation recalculaient depuis des constantes — changer les valeurs aurait retarifé rétroactivement toutes les commandes passées. Grille DATÉE : chaque ligne porte la date de sa commande, posée une fois et jamais rafraîchie ; une ligne sans cette marque retombe sur l'ancienne grille (aucune migration nécessaire). Verrous : aucun repli sur la date du jour (date absente → ancienne grille) ; la grille prime sur le catalogue produits ; bandeau visible annonçant la grille appliquée. Tarifs : coffrets 14/18/22/34/50 €, sachet 2,50/5/6,50 €, événement 1,90 €, pyramide 22 €, pro occasionnel 1,75 € et pro récurrent 1,60 €, perso couleurs 0,30 €. Options nouvelles : logo dégressif (1 / 0,80 / 0,70 €) et forfait création 40 € PAR MODÈLE, visibles sur devis et factures. Suite v1463 : 52 assertions, scénario d'antidatation inclus, sensibilité vérifiée par mutation.
// [v1462] MACARONS : LA CARTE ET LE DÉTAIL ARRONDISSAIENT SÉPARÉMENT. Ben : « si tu additionnes l'ensemble ça ne fait pas 318 ». Vrai bug d'arrondi : un paiement partiel proratise les macarons (fraction) — la carte arrondissait le TOTAL brut, le détail arrondissait CHAQUE LIGNE séparément. Arrondir un total et additionner des arrondis ne donnent pas toujours le même résultat (paradoxe de répartition classique). FIX : chaque ligne est arrondie à la source dans caDuMois, le total est la somme de ces entiers déjà arrondis — jamais un second arrondi indépendant. Suite v1462 : 34 assertions, dont une reconstitution exacte du cas de Ben et une réconciliation vérifiée sur 30 tirages aléatoires ; sensibilité confirmée par mutation réelle.
// [v1461] LES MACARONS VENDUS COMPTÉS AU MÊME ENDROIT QUE LE CA. Ben : « ils ne comptent pas les marchés » et « même isolés du marché le compte semble faux ». CAUSE RACINE : le tableau de bord refaisait sa PROPRE addition à côté de celle du CA — deux écritures de la même règle, qui divergeaient sur le périmètre des marchés et sur le prorata des paiements partiels. Le compte vit désormais DANS caDuMois : un seul calcul, lu par la carte comme par le détail. RÉVÉLÉ AU PASSAGE : un marché peut être clos sans aucun comptage de sortie/retour (la clôture ne demande que les encaissements) — ses macarons sont alors INCONNUS, pas nuls. L'app les additionnait comme 0 ; elle le signale maintenant (avertissement sur la carte, « non compté » sur la ligne du marché). DEMANDE DE BEN : chaque ligne du détail du CA affiche son nombre de macarons à côté du pourcentage. Suite v1461 : 30 assertions ; la suite v1459 (dont le sujet n'existe plus) est retirée après portage de ses cas.
// [v1460] MACARONS VENDUS DU MOIS : DEUX DÉFAUTS CORRIGÉS (corrige la v1459). Ben : « je la vois mais le chiffre me paraît faux ». ① PÉRIODE INCOHÉRENTE avec le CA de la MÊME carte : les macarons comptaient les commandes DATÉES du mois, le CA les ENCAISSEMENTS — une commande de juillet payée en août montrait son CA en août et ses macarons en juillet. ② DOUBLE COMPTAGE mère/fille : un paiement d'avance (mère) puis des retraits successifs (filles, chacune avec ses lignes) étaient tous comptés. CHOIX DE BEN : base « encaissé », comme le CA — ce qui règle ② à la racine (une fille n'a jamais de paiement propre). Paiement partiel → prorata du montant encaissé, ratio plafonné à 1. Total arrondi une seule fois. La date du jour était déjà affichée sur le bandeau Tableau de bord : vérifié avant de coder, rien ajouté. Suite v1459 : 20 assertions, sensibilité vérifiée par mutation réelle (8 rouges).
// [v1459] MACARONS VENDUS SUR LE MOIS + DATE DU JOUR. Ben : « afficher sur l'écran d'accueil le nombre de macarons vendus sur le mois ? Et sur le tableau de bord indiquer la date du jour, pas seulement le mois ? ». La carte « CA du mois » affiche le nombre de macarons vendus (part marché distinguée) ; le bandeau indique jour de la semaine + jour + mois + année. PIÈGE ÉVITÉ : « vendus » ≠ « sortis ». orderTotalMacarons compte DONS COMPRIS (voulu : il lie les lots de production, un macaron offert quitte bien le stock) — le réutiliser aurait fait passer les dons pour du CA. Compteur distinct écrit, les deux coexistent. Reprises d'historique exclues. Règle du « vendu » des marchés réutilisée, pas redite. Période = date de la commande (comme le compteur de commandes voisin), pas la date d'encaissement : un paiement partiel ne dit pas quels macarons il couvre. Suite v1459 : 27 assertions, sensibilité vérifiée par mutation.
// [v1458] ÉTIQUETTE SPÉCIALE RETOUR MARCHÉ — ET LA QUANTITÉ QUI MANQUAIT. Ben : « l'app me propose d'editer une étiquette spéciale retour marché ». Mention « RETOUR MARCHÉ » sur les DEUX moteurs d'étiquette (canvas/PDF et HTML), juste sous le nom du produit, en noir plein inversé (lisible sur thermique monochrome). Après le rangement d'un retour, l'app propose les étiquettes des boîtes créées et signale en rouge celles SANS DLC — à renseigner avant de vendre, l'app n'en invente pas. DÉFAUT PLUS GRAVE TROUVÉ AU PASSAGE : la QUANTITÉ n'était pas imprimée du tout par le rendu HTML (bien calculée, bien dessinée par le moteur canvas/PDF, mais omise là) — l'étiquette « recyclable » de la v1454, où Ben corrige la quantité au stylo, n'avait donc rien à corriger sur ce chemin. Le correctif v1454 changeait QUELLE quantité est calculée sans voir qu'elle n'était jamais affichée. Corrigé. Suite v1458 : 25 assertions, sensibilité vérifiée par mutation réelle.
// [v1457] RETOURS DE MARCHÉ : RANGER LES INVENDUS EN BOÎTES. Ben : « dans l'onglet retour marché je saisi les quantités retour de chaque parfums ; l'app fait le delta puis propose de ranger chaque quantité pour chaque parfums. Sur cet écran je choisi une répartition par boîte […] puis l'emplacement pour les ranger proprement et distinctement ». L'écran existait déjà (saisie par parfum, delta pré-calculé, congélateur/frigo/écarté, recongélation interdite si déjà décongelé) ; il gagne une 2e ÉTAPE de rangement : une ligne = une boîte, avec quantité, emplacement et rattachement. DÉFAUT CORRIGÉ : la provenance était réduite au PREMIER lot sorti (« compat affichage ») — un lot pouvait récupérer plus de pièces qu'il n'en avait fourni. Chaque lot est désormais plafonné à ce qu'il a donné, le surplus devient une ligne « RETOUR MARCHÉ » (-RM, étiquette spéciale). DÉCISIONS DE BEN : DLC d'origine CONSERVÉE (avant, un retour au congélateur la PROLONGEAIT alors que les macarons venaient de passer la journée dehors) ; provenance inconnue → ligne non rattachée ; boîtes d'origine recréditées en priorité. DLC d'une ligne non rattachée = la plus courte des lots sortis, et VIDE si aucune n'est connue plutôt qu'inventée. Suite v1457 : 40 assertions, réconciliation « un lot ne récupère jamais plus qu'il n'a fourni », sensibilité vérifiée par mutation réelle.
// [v1456] RÉIMPRIMER L'ÉTIQUETTE APRÈS UNE FUSION. Ben : « en cas de fusion de boîte je dois pouvoir réimprimer une étiquette mise à jour ». La fusion est le cas particulier : sur un prélèvement Ben corrige au stylo (étiquette « recyclée »), mais après une fusion il n'y a rien à corriger à la main — la boîte gardée contient d'autres pièces qu'annoncé, sa DLC a pu raccourcir, et l'étiquette de l'absorbée n'a plus d'objet. Réimpression PROPOSÉE au moment où elle devient nécessaire, quantité et DLC réelles affichées avant d'imprimer, jamais imposée. Le NUMÉRO DE LOT ne change pas (le QR encode l'adresse bâtie dessus : le faire varier tuerait toutes les étiquettes déjà imprimées) — réimpression, pas nouvelle identité. Ajouté aussi : bouton « 🖨 Étiquette » permanent par boîte, pour réimprimer à tout moment. Suite v1456 : 19 assertions, dont la garde que la proposition n'écrit rien en base ni ne régénère de numéro ; sensibilité vérifiée par mutation réelle.
// [v1455] TRANSFÉRER DES MACARONS D'UNE BOÎTE À UNE AUTRE. Ben : « je dois pouvoir facilement transférer manuellement un ou plusieurs macarons d'une boîte à une autre (pour gérer les erreurs de saisies) ». Audit préalable : répartition en boîtes et casse existaient déjà (declareLossForm, 4 stades, bouton Perte par boîte) — seul le transfert PARTIEL manquait, la fusion vidant toujours une boîte entièrement. Bouton « ⇄ Transférer » par boîte. Règles : même lot obligatoire ; transfert total = boîte de départ ARCHIVÉE (pas laissée vide) ; DLC d'arrivée = la plus courte des deux. Le fil de traçabilité rend les transferts dans les DEUX sens, avec une icône distincte de la fusion et un lien vers l'autre boîte. Suite v1455 : 34 assertions, réconciliation « aucune pièce créée ni perdue », sensibilité vérifiée par mutation réelle.
// [v1454] ASSEMBLER UN LOT DE COQUES RÉPARTI EN PLUSIEURS BOÎTES. Ben : « si j'ai 200 coques réparties en 6 boîtes je dois faire mon assemblage à 6 reprises, alors que dans la réalité je sors l'ensemble des coques de leurs boites […] les dispose sur mon plan de travail et les garnis ensuite ». Le bouton « Assembler » de Stock par parfum devient « Assembler tout le lot (N boîtes) » : il regroupe les boîtes puis ouvre le formulaire d'assemblage habituel sur la ligne unique obtenue. Le moteur d'assemblage n'est PAS touché — étape amont qui réutilise le moteur de fusion éprouvé, en UNE transaction (une sauvegarde, une écriture atomique, un audit) au lieu de N-1 fusions. Boîtes absorbées ARCHIVÉES, jamais supprimées. DLC retenue = la plus courte. AU PASSAGE : l'étiquette imprime la quantité QUI RESTE et non la produite — Ben veut une étiquette « recyclée » (corrigée au stylo, QR renvoyant à la quantité réelle du moment) ; partir de la produite la rendrait fausse dès l'impression sur une boîte issue d'un lot entamé. Suite v1454 : 33 assertions, réconciliation « aucune coque créée ni perdue », sensibilité vérifiée par mutation.
// [v1453] SUPPRIMER UNE CHARGE DEPUIS SA FICHE. Ben : « je veux pouvoir supprimer des charges en cas d'erreur de saisie. 3 lignes identifiées dans « autre » à supprimer (ligne marketing Entreprenance, année passée, et celle qui démarre en septembre) ». La suppression existait déjà (delCharge, via « Voir / gérer les charges ») mais nulle part dans la fiche d'une charge elle-même, là où on repère l'erreur en la relisant. FIX : bouton Supprimer directement dans le formulaire d'édition, visible pour une charge existante. « Celle qui démarre en septembre » sent la charge récurrente : supprimer l'instance ne corrige pas une date de départ fausse sur le modèle, qui la regénérerait chaque mois — rappel explicite ajouté avec accès direct à l'éditeur des charges récurrentes. Suite v1453 : 14 assertions, rendu réel vérifié dans les 3 cas, sensibilité confirmée par mutation.
// [v1452] SACHET (1 à 3 macarons, 2,50 €/macaron) ET COFFRET DE 10 À 22 €. Ben : « Rajouter offre dans commande permettant de vendre : un coffret de 10 macarons à 22€. L'emballage par défaut est la boîte blanche de 8/10 macarons. Assure toi de rendre les autres emballages selectionnables aussi telle que c'est déjà le cas aujourd'hui. — un sachet pouvant contenir de 1 à 3 macarons. Prix : 2,5€ par macaron. De manière générale introduire ce nouvel emballage dans tous les écrans de commande, y compris vrac. » SACHET : nouveau type de ligne complet (bouton « + Sachet », grille de parfums avec compteur de remplissage, « sans parfum » supporté, remise, validation 1–3). Un type de ligne est lu par ~137 endroits et un type inconnu ne plante pas — il est ignoré en silence ou tombe dans un repli prévu pour autre chose ; le sachet a donc été branché un par un : enregistrement/réouverture, prix en saisie ET prix stocké, besoins production, coût matières et marge, factures/devis, export, analytics, et sa propre catégorie de mix produit (sinon compté parmi les DONS à 0 €). COFFRET 10 : migration idempotente distincte du seed initial (qui ne s'exécute que sur un catalogue vide), création de la boîte blanche 8/10 si absente, pré-sélection de cet emballage à la taille 10 — un défaut, pas un verrou. Suite v1452 : 42 assertions, réconciliation prix saisie/stocké + aller-retour enregistrement→réouverture + garde « jamais 0 € », sensibilité vérifiée par mutation réelle.
// [v1451] POURCENTAGE DE CA — SUITE, 3 ÉCRANS DE PLUS. Continuation directe de v1450, recherche systématique au-delà de l'exemple littéral de Ben. Trois écrans de plus où une liste de transactions somme à un total CA visible : « CA facturé »/« CA encaissé » par période (comptaFluxDetail — reprises d'historique et total officiel gardés séparés, chacun son propre pourcentage) ; journal des avoirs émis (renderAvoirs) ; détail des commandes du panier moyen ventilé (renderPanierMoyen, contre le total déjà affiché). Écartés : cartes de règlement par commande (pas de total de groupe) et listes d'anomalies (le montant n'est pas censé sommer à un total). Suite v1451 : 9 assertions.
// [v1450] POURCENTAGE DE CA DEVANT CHAQUE TRANSACTION. Ben : « je veux qu'à chaque fois que c'est possible, devant chaque transaction ça indique le pourcentage de CA que ça représente sur la totalité du calcul réalisé. Exemple quand je clique sur CA du mois, et que je clique sur le détail du CA encaissé, chaque commande indique le pourcentage que ça représente sur la totalité du calcul. » FIX : un pourcentage s'affiche sous le montant de chaque ligne, sur les 3 écrans de détail CA/encaissement — détail du mois, détail d'une période glissante (jour/semaine/année), détail d'une catégorie du bilan URSSAF. Un seul calcul partagé (pctDuTotal) : une ligne négative (reprise, avoir) affiche un pourcentage négatif, pas sa valeur absolue. Respecte le mode confidentialité. Second point de Ben (nom du client systématique, pas un numéro) : déjà en place sur les 3 écrans, vérifié plutôt que re-modifié. Suite v1450 : 19 assertions, dont une réconciliation (somme des pourcentages ≈ 100 %).
// [v1449] UN PARFUM BICOLORE COMBINÉ À D'AUTRES SE DIVISE AUSSI. Ben, en réaction à v1445/v1448 : « si j'ai 240 coques et que je souhaite mutualiser la meringue à part égale entre pistache et chocolat passion je devrais faire : Pistache = 120 coques / Chocolat passion = 60 coques marrons + 60 coques orange. Ainsi la recette doit s'ajuster en conséquence. » La division bicolore (v1445) ne gérait qu'UN parfum, à part, sur une case à cocher. FIX : nouveau moteur partagé (_sousLotsCoques) qui décide, pour CHAQUE parfum d'un lancement coques ou d'une meringue commune (duo/trio), s'il produit 1 lot (mono-couleur) ou 2 (bicolore, toujours 50/50) — seul ou combiné à d'autres. Case à cocher supprimée : plus une option, un comportement systématique. Récapitulatif, numéros de lot prévisualisés et détail des ingrédients reflètent tous les vrais sous-lots (jusqu'à 6 dans un trio entièrement bicolore). Suite v1449 : 28 assertions, dont la reproduction exacte du scénario chiffré de Ben (120/60/60, 240 coques), lancement réel et aperçu, sensibilité vérifiée par mutation réelle.
// [v1448] LE CHAMP « N° LOT DE PRODUCTION » MENTAIT EN MODE DUO. Ben, capture à l'appui : lançant Chocolat passion + Pistache en meringue commune, le champ affichait « 030826RAF » (Coco Rafaello, une tout autre recette). CAUSE : la branche duo de saveProd() ne lit jamais ce champ — chaque parfum reçoit son propre lot calculé indépendamment. Sa valeur venait de prodRefreshLot(), qui lit toujours la recette unique (f_rec), restée dans la page (masquée) avec la valeur de la DERNIÈRE recette affichée avant le passage en duo. Même défaut, plus discret, sur la case « diviser en 2 lots » (v1445/v1446). FIX : le champ est masqué dans ces deux cas ; les vrais numéros de lot sont prévisualisés à la place (récapitulatif duo, encart bicolore), calculés avec exactement la même formule que la sauvegarde réelle. Suite v1448 : 12 assertions, dont une réconciliation qui rejoue la vraie formule et vérifie 030826CHP-CO / 030826PIS-CO — jamais RAF.
// [v1447] CODES COULEUR DES LOTS : EXPLICITES, PLUS ALGORITHMIQUES. Ben : « je veux que le code pour la coque blanche dise BLA et pas BAN ». Le code court des numéros de lot était calculé automatiquement (filtre I/L/O retire le L de BLANC → BAN). En creusant plus loin : ce calcul faisait aussi atterrir les 4 marrons sur « MAR », les 2 rouges sur « RUG », les 2 verts sur « VER », les 2 jaunes sur « JAU » — deux couleurs différentes, un même code de lot, silencieusement indiscernables. FIX : table explicite (même principe que FLAVOR_CODES) donnant à chacune des 14 couleurs un code lisible et unique — blanc → BLA, plus aucune collision. Repli algorithmique conservé pour une couleur future non cataloguée. Suite v1445 amendée (section A) : code du blanc, absence de collision sur les 14 couleurs, repli couleur inconnue — sensibilité confirmée par réintroduction réelle.
// [v1446] LA CASE « DIVISER EN 2 LOTS » SE DÉCOCHAIT TOUTE SEULE. Ben, captures à l'appui : une fiche « Chocolat passion » montrant un seul lot (sans suffixe de couleur) avec le simple rappel v1441, alors qu'il pensait avoir demandé la division. CAUSE : prodUpdateCoqueHint() reconstruit ENTIÈREMENT la case à cocher à chaque appel, y compris depuis le champ Quantité (qui l'appelle à chaque frappe depuis v1441) — le nouvel <input> ne portait jamais l'état précédent, donc cocher la case puis toucher la quantité la redécochait en silence. FIX : l'état est lu avant destruction et reporté sur la nouvelle case. Suite v1445 amendée : 3 assertions, dont la preuve par réintroduction du symptôme exact.
// [v1445] DIVISER UN PARFUM BICOLORE EN 2 LOTS, COMME UNE MERINGUE MUTUALISÉE. Suite de v1441 : Ben a essayé le simple rappel et signalé que ça ne suffisait pas — « Praliné ne se divise pas en 2 comme souhaité […] je dois avoir d'un côté une couleur de coque puis de l'autre côté la deuxième couleur […] la même chose que si je décidais de scinder ma meringue en 2 pour faire vanille et chocolat au lait ». FIX : le formulaire (mode Composant → Coques) propose désormais de diviser une recette bicolore en 2 LOTS RÉELS séparés — chacun sa quantité, sa DLC, son suivi de stock propre — reliés comme une fournée de meringue commune, exactement le mécanisme du mode duo appliqué à un seul parfum divisé par couleur plutôt qu'à 2 parfums différents. Toujours 50/50. Absent en mode « Batch complet » (le mode duo lui-même ne gère que les coques). SOUS LE CAPOT : un lot peut porter une couleur EXPLICITE prioritaire sur les 2 couleurs de sa recette — les 3 moteurs qui lisent la couleur d'un lot (stock potentiel, suggestions d'assemblage, suggestions de dégustation) la respectent désormais, pour qu'un lot déjà divisé ne soit jamais re-divisé virtuellement une seconde fois. Suite v1445 : 31 assertions, dont 2 réconciliations dissymétriques (100 marron / 140 blanc) vérifiées sensibles par mutation réelle de app.js à 3 endroits séparés.
// [v1444] GRAPHIQUE DU CA ZOOMABLE ET GLISSANT (modèle : l'app Santé d'iPhone). Ben voulait pouvoir dézoomer le graphique de l'accueil (tranche d'1 an au lieu des 6 mois figés), zoomer (mois, semaine), et faire glisser la période par défilement horizontal, tout en gardant chaque résultat cliquable. FIX : bande défilante + 4 onglets Jour/Semaine/Mois/Année ; l'onglet choisit la largeur d'une barre, le défilement fait glisser la fenêtre à granularité constante, ouverture sur la période la plus récente. « Mois » = 12 barres = la tranche d'1 an citée en exemple. Chaque barre ouvre le détail de SA période (un mois ouvre l'écran mensuel habituel, inchangé). Période sans vente = barre à zéro, jamais absente. LIMITE DÉCLARÉE : un encaissement porte une date, jamais une heure — la barre la plus fine est le JOUR, pas d'heure par heure. L'accueil ne lance plus 6 requêtes caDuMois par rendu (un seul passage, regroupement côté client). Suite v1444 : 35 assertions, dont la réconciliation mois par mois avec caDuMois (source unique de vérité) — testée sensible par mutation.
// [v1443] LE CHAMP « MACARONS Pn » NE SUIVAIT PAS LE PARFUM CHOISI. Ben, capture à l'appui : en mode duo, choisir « Coco citron vert (100/batch) » en Parfum 2 laissait « Macarons P2 » à 60 — jamais resynchronisé sur le rendement du parfum réellement choisi (« 100/batch » écrit au-dessus, « 60 » dedans). Le mode mono-parfum avait déjà ce réflexe (prodSyncTheorique) ; il manquait sur les 3 emplacements du mode duo/trio. FIX : prodDuoSyncQte(slot), branchée sur les 3 sélecteurs — la quantité suit désormais le rendement du parfum choisi, total/répartition recalculés aussitôt ; « — aucun — » en Parfum 3 remet sa quantité à 0. Suite v1443 : 9 assertions.
// [v1442] LA FICHE MERINGUE MUTUALISÉE, ACCESSIBLE À TOUT MOMENT. Ben : « je dois pouvoir accéder à la recette donnant la quantité totale de meringue mutualisée au même titre que le reste de la recette […] disponible à tout moment à l'intérieur de ce bouton-là présent en haut de la page fabrication ». Le calcul (base commune cumulée + détail propre de chaque parfum, une seule vue) existait depuis la v1379/v1380 mais ne s'affichait qu'UNE fois, juste après le lancement d'un duo — ensuite, « Voir la recette » sur un sous-lot ne montrait plus que CE parfum. FIX : un batch relié à une fournée de meringue commune rouvre désormais la fiche COMBINÉE depuis le même bouton, à tout moment. Suite v1442 : 15 assertions.
// [v1441] RAPPEL DE DIVISION BICOLORE. Ben : pour un parfum bicolore (praliné = marron foncé + blanc), il devait passer par le mode « duo » (2-3 parfums) et simuler un faux 2e parfum juste pour voir un sélecteur de couleurs. Décision (2 questions posées) : un seul lot de coques, toujours 50/50, juste un rappel clair. FIX : dès qu'une recette bicolore est sélectionnée, rappel affiché dans le formulaire de lancement (désormais aussi en mode « Batch complet », le mode par défaut, jusqu'ici sans aucune info couleur) ET dans la fiche de production TOUJOURS affichée après lancement — « divise ta meringue en 2 portions égales — 60 coques marron foncé + 60 coques blanches ». Split toujours entier exact. Suite v1441 : 15 assertions (tests/v1441-bicolore-rappel.test.js).
// [v1440] LE BOUTON « ＋ LANCER UNE TÂCHE », RÉPARÉ MAIS INVISIBLE. Suite directe de v1439 : Ben a signalé que le bouton ne plantait plus mais que « quand je clique dessus plus rien ne se passe ». CAUSE : le sélecteur s'ouvrait bel et bien (même mécanisme que le bouton ▼ « Voir toutes les tâches », qui fonctionnait déjà) mais plus bas dans l'écran, sans repère visuel — et `_atPicker` n'étant jamais remis à `false` par un simple rechargement de vue, un clic alors que le sélecteur était déjà ouvert d'un essai précédent ne changeait RIEN à l'écran. FIX : `prodBoardLaunch()` attend le rendu puis fait défiler la liste dans le cadre (repli sur le bloc suggestion si la liste est vide) — un clic a désormais TOUJOURS un effet visible. Suite v1439 amendée : 14 assertions, dont la preuve par réintroduction du symptôme exact de ce second rapport.
// [v1439] LE BOUTON « ＋ LANCER UNE TÂCHE » DE L'ATELIER COMPLET N'OUVRAIT RIEN. Signalé par Ben, capture du journal d'incident à l'appui : « GLOBAL onerror @app.js:61626 Can't find variable: prodTaskPicker », écran atelier. CAUSE : `prodBoardLaunch()` (le gestionnaire du bouton marron) appelait `prodTaskPicker()` — un sélecteur MODAL qui n'a jamais existé dans app.js. Un commentaire prétendait le contraire (« Réutilise […] prodTaskPicker ») : documentation fausse, contributrice directe à ce que le bug soit passé inaperçu à la relecture. Le vrai sélecteur, depuis le passage à la « couche flottante » (v1364, « sans ouvrir de modale »), s'ouvre en posant `_atPicker = true` puis en redessinant le board — exactement ce que fait déjà `atTogglePicker()` pour le panneau flottant jumeau, qui lui fonctionnait normalement. FIX : `prodBoardLaunch()` ouvre désormais le même mécanisme réel ; le commentaire fautif corrigé. Suite v1439 : 7 assertions (tests/v1439-prodboard-launch.test.js), garde statique anti-réintroduction du nom + comportement vérifié en isolation + preuve par réintroduction (l'ancien appel reproduit lève le ReferenceError exact vu par Ben).
// [v1438] LA COURSE AU DÉMARRAGE (chiffres au lieu des parfums / Productions qui plante). Ben a repéré, captures + rapport d'incident à l'appui : au lancement, des batchs s'affichaient avec leur numéro brut au lieu du nom du parfum, et l'écran Productions plantait parfois (« Affichage indisponible »), tous deux avec la même erreur IndexedDB (« The transaction finished » / « The specified object store was not found »). CAUSE : dans dexie.min.js, `_activeTx` (la transaction « en cours ») est un champ PARTAGÉ sur toute l'instance Dexie, pas propre à chaque appel. Au boot, plusieurs opérations tournent concurremment (migrations, flush différé du journal d'audit via Dexie.ignoreTransaction) ; une opération pouvait hériter par erreur de la transaction d'un AUTRE appel — déjà terminée, ou ne portant pas la table visée. atParfumsDispo() avalait cette erreur (`.catch(()=>[])`) → repli sur une liste de recettes vide → chaque batch affichait `'#'+id` (148 occurrences dans le journal, écran atelier). Sur Productions, la même erreur n'était pas rattrapée → écran entier en échec. FIX (uniquement dans dexie.min.js, zéro changement à app.js) : `_txStore()` vérifie désormais que la transaction partagée est encore VIVANTE et porte bien la table demandée avant de la réutiliser ; sinon elle ouvre sa propre transaction dédiée au lieu de laisser `tx.objectStore()` planter sur une transaction morte ou étrangère. Preuve par réintroduction : tests/v1438-activeTx-course.test.js (7 assertions) rejoué contre l'ancien fichier replante bien sur les deux messages d'erreur exacts observés par Ben ; rejoué contre le fichier corrigé, tout passe, y compris la non-régression sur une transaction explicite multi-tables légitime (atomicité conservée).
// [v1386] CHANTIER D — DURCIR LA FRONTIÈRE QR (faille 4 de l'audit de juillet 2026). L'app a quatre frontières : la saisie clavier (gardée v1373), le fichier de sauvegarde (gardé v1384), le réseau R&D, et LE QR CODE — qui n'avait AUCUN contrôle, alors que c'est la seule que Ben franchit les mains pleines, en atelier, sans regarder l'écran. QUATRE FAITS VÉRIFIÉS : (1) _extractLot() JETAIT sur une étiquette abîmée — decodeURIComponent('%E0%A4%A') lève URIError ; (2) dans scanLoop() ce jet était avalé par le catch « frame non décodée, on continue », donc le scanner repartait EN BOUCLE SANS RIEN DIRE : Ben visait dans le vide en croyant que la caméra ne voyait pas le code, alors que l'app l'avait lu, avait planté et avait jeté l'erreur en silence — le motif du chantier A sur la frontière la moins surveillée ; (3) dans onScan() (h5-qrcode) AUCUN try, le jet remontait dans une callback de librairie tierce, scanner ouvert et figé ; (4) la recherche compare par INCLUSION (full.includes(target)), donc un QR ne contenant qu'un tiret correspondait à TOUS les lots — sur un écran « Quel lot ? » c'est une invitation à décrémenter le mauvais stock, et en traçabilité alimentaire se tromper de lot n'est pas une erreur d'affichage. CE QUI EST FAIT : une porte unique _qrLire() qui NE JETTE JAMAIS et rend un verdict explicite {ok, lot, motif} ; bornes justifiées (200 caractères = dix fois un n° de lot réel ; jeu de caractères réellement produit par le générateur d'étiquettes ; minimum 2 caractères pour une recherche par inclusion, prouvé nécessaire) ; _extractLot délègue désormais à la porte et rend '' au lieu de jeter — trou fermé à la SOURCE plutôt que site par site, parce que patcher les cinq appelants aurait laissé le sixième, écrit plus tard, retomber dedans ; les trois entrées (caméra native, h5-qrcode, saisie manuelle) et les deux recherches par inclusion passent par la porte ; tout refus est affiché ET journalisé sous le contexte « qr » dans l'écran Santé du chantier A. CE QUI N'EST PAS FAIT, délibérément : refuser un lot inconnu (un QR bien formé sans correspondance est un fait légitime, on le DIT sans le traiter comme une attaque) et deviner un lot proche (« NM-A-1O1 » n'est PAS corrigé en « NM-A-101 » : proposer le mauvais lot avec assurance est pire que dire « je ne trouve pas » — même règle qu'au chantier B). Règle figée : un code venu de l'extérieur n'est jamais une donnée tant qu'il n'a pas passé une porte qui peut dire NON, et le refus doit se VOIR. Suite v1386 : 58 assertions, vérifiées par 6 sabotages dont la réintroduction de la faille d'origine. Les quatre chantiers de l'audit sont livrés.
// [v1385] CHANTIER C — SORTIR LES SAUVEGARDES DE LA BOÎTE QU'ELLES PROTÈGENT (faille 3 de l'audit de juillet 2026). TROIS FAITS. (1) snapshotBackup() écrit dans db.backups — la MÊME base IndexedDB que les données protégées : le danger que l'app nomme elle-même partout (« effacer l'historique Safari supprime aussi la base ») emporte les 20 instantanés AVEC les données. Une copie qui meurt quand meurt l'original n'est pas une sauvegarde. (2) exportData() faisait `a.click(); localStorage.setItem('sm_lastExport', today());` alors que le commentaire juste dessous admettait « l'app ne peut PAS savoir si la sauvegarde a été confirmée » — un partage annulé d'un geste éteignait donc le rappel SEPT JOURS et remettait le compteur de travail non sauvegardé à zéro. C'est le motif exact de « 0 refus, 0 suspects » : un écran calme dont le calme signifie que rien n'a été vérifié. (3) Une seule clé portait deux sens : « j'ai demandé » et « c'est fait ». CE QUI EST FAIT : deux états distincts et jamais confondus — sm_lastExportTente (fait observable : fichier remis à iOS) et sm_lastExport (fait CONSTATÉ par Ben, seul état qui éteint le rappel) ; une demande de confirmation après CHAQUE sortie (export, partage iCloud, repli téléchargement, téléchargement d'un instantané), honnête sur son ignorance — répondre « annulé » ne pénalise rien ; l'âge réel de la dernière sortie confirmée affiché en clair, avec mention explicite d'une tentative plus récente restée non confirmée ; une date de sortie ILLISIBLE est traitée comme un RISQUE, jamais comme un succès ; et l'écran Sauvegardes dit désormais que les instantanés internes protègent d'une fausse manœuvre mais PAS d'une purge iOS ni d'un téléphone perdu. CE QUI N'EST PAS FAIT, déclaré : une PWA iOS ne peut pas vérifier qu'un fichier est arrivé dans iCloud Drive — aucune API ne le permet ; on ne remplace donc pas une supposition optimiste par une autre, on rend la différence VISIBLE et c'est Ben qui tranche, parce que lui a vu l'écran. Règle figée : une sauvegarde n'est acquise que lorsqu'elle est SORTIE de l'appareil, et une sortie n'est acquise que lorsqu'elle est CONSTATÉE — jamais parce qu'on l'a demandée. Suite v1385 : 46 assertions, vérifiées par 4 sabotages dont la réintroduction de la faille d'origine. Reste : chantier D.
// [v1384] CHANTIER B — VALIDER LE CONTENU À L'IMPORT (faille 1 de l'audit de juillet 2026). LE CONSTAT, démontrable : la v1373 a posé des schémas de validation sur 21 tables via les hooks Dexie, mais applyDump() et mergeDump() posent `_importEnCours = true` et les deux hooks commencent par `if(_importEnCours) return;`. Le seul contrôle de CONTENU de l'app était donc ÉTEINT sur la seule porte par laquelle entrent des données que Ben n'a pas tapées lui-même : la saisie manuelle était gardée, le fichier venu d'iCloud ou d'un vieux téléphone entrait sans contrôle. verifyBackup() ne juge que la FORME (tableaux, doublons d'id, somme de contrôle) — un montant en chaîne ou une date malformée passaient intacts. POURQUOI ON NE RALLUME PAS LES HOOKS : la suspension est JUSTE, une exception dans un hook avorte la transaction ENTIÈRE, donc une seule fiche bancale de 2024 rendrait toute la sauvegarde irrécupérable — pire que pas de contrôle le jour où le téléphone est cassé. Donc valideDumpAvantImport() valide AVANT la transaction, sur le dump en mémoire, et RÉPARE au lieu de refuser. Réparations UNIQUEMENT non ambiguës : "32,50"→32.5 (virgule française), nombre resté en chaîne, "true"→true, JJ/MM/AAAA→AAAA-MM-JJ, ISO→jour. JAMAIS réparé, car ambigu ou inventé : séparateur de milliers, deux séparateurs, hexadécimal ("0x1A" ne devient PAS 26 €), notation exponentielle, mois hors bornes (aucune bascule MM/JJ par supposition), et surtout AUCUN champ requis absent n'est complété — inventer une donnée dans une sauvegarde serait le mensonge que ce projet combat. Chaque réparation est listée avant/après dans le rapport de confirmation ET journalisée (op « import-controle ») : un rapport lu une fois puis évaporé ne prouve rien le lendemain (règle v1383). Décision volontairement asymétrique : les anomalies non réparables n'empêchent PAS l'import, elles sont comptées et annoncées — c'est Ben qui tranche, informé. Aucune fiche n'est jamais supprimée ni vidée. Les schémas v1373 sont RÉUTILISÉS, pas dupliqués (un second jeu divergerait). Suite v1384 : 59 assertions, dont les cas prouvés par mutation — mes premiers cas ambigus passaient au vert avec le filtre RETIRÉ (Number() les rejette déjà), seuls "0x1A"/"1e3"/"Infinity" font vraiment travailler la protection. Reste : chantiers C et D de l'audit.
// [v1383] CHANTIER A — LES ÉCHECS SILENCIEUX DEVIENNENT VISIBLES. Suite directe de l'audit de juillet 2026. Le constat : 347 appels à swallow() enregistraient fidèlement chaque erreur, dans un anneau EN MÉMOIRE, affiché NULLE PART — il fallait brancher l'iPhone sur un Mac pour en lire une seule, et tout était effacé à chaque rechargement. C'est le mécanisme exact qui a caché la panne Dexie pendant un mois (chaque écriture kv échouait, la validation ne démarrait jamais, et l'écran affichait « 0 refus, 0 suspects » — ce qui ressemblait à une bonne nouvelle alors que ça voulait dire « le contrôle n'a jamais démarré »). Ajouté : (1) table errLog (schéma v33) — les incidents vivent EN BASE, donc survivent à un rechargement, donc prouvent qu'une panne DURE ; (2) écran « Santé de l'app » dans Sauvegarde & sécurité — lisible depuis le téléphone, sans Mac, groupé par signature avec compteur ; (3) filet global (window.onerror + unhandledrejection) — une erreur hors try/catch donnait un écran figé sans trace, elle est désormais enregistrée et annoncée ; (4) pastille d'accueil quand des incidents IMPORTANTS s'accumulent. Le tri est le cœur du travail : base, sauvegarde, import, validation, compta → important ; rendu et affichage → mineur. Confondre les deux noierait le signal sous le bruit, et une alerte qui crie tout le temps n'est plus regardée. Écriture en base JAMAIS synchrone depuis swallow() (il est appelé dans des catch, parfois pendant que la base casse) : file d'attente bornée + vidage différé protégé, qui n'appelle jamais swallow() lui-même. Règle figée : une protection qu'on ne peut pas VOIR marcher doit être considérée comme ABSENTE jusqu'à preuve du contraire. Suite v1383 : 38 assertions, dont la garde qui exige que les 5 contextes de la panne Dexie déclenchent tous la pastille. Reste : chantiers B, C, D de l'audit.
// [v1381] LE MOTEUR — dexie.min.js ne tenait pas le contrat : un mois de protections mortes, réparé. Découverte grâce à Ben (il a partagé le vrai runtime, jamais présent dans les zips) : la micro-implémentation Dexie de prod ne fournissait ni table.hook(), ni db.tables, ni bulkPut/bulkDelete, ni primaryKeys, ni Dexie.ignoreTransaction. Conséquences vérifiées : la table kv est restée VIDE un mois (chaque flush du stockage unifié échouait — compteur de factures, pyramides, journal copilote jamais recopiés en base) ; le journal d'audit et la validation à l'entrée n'ont JAMAIS tourné (auditInstalle/valideInstalle plantaient au boot, erreur avalée). Aucune perte de données (fusion, devis, parfum par tâche écrivent en direct). Correctif : le contrat est désormais tenu PAR LE MOTEUR (zéro changement à app.js) — hooks creating/updating/deleting (multi-abonnés, this.onsuccess(id), une exception AVORTE l'opération et sa transaction), enveloppe trans.on('complete') (tampon d'audit flushé une fois au commit), put=upsert, bulkPut/bulkDelete, primaryKeys, between/anyOf, db.tables, db.on('blocked'), db.close/open, Dexie.ignoreTransaction (macrotâche, divergence déclarée). Divergences documentées en tête de fichier. Nouvelle classe de preuve : tests/_faux-idb.js charge LE fichier dexie.min.js livré (via vm) sur un IndexedDB mémoire — suite v1381 (28 assertions) jusqu'au bout-en-bout réel : valideInstalle+auditInstalle extraits d'app.js sur le vrai moteur, montant en chaîne refusé et journalisé, création saine journalisée avec sa clé, rollback tout-ou-rien prouvé. Règle gravée : un test qui fournit lui-même l'API qu'il prétend vérifier ne vérifie rien. dexie.min.js fait désormais partie de chaque zip. Vérif post-déploiement : écran Sauvegarde & sécurité → le compteur kv doit passer de 0 à ~18 clés au premier démarrage.
// [v1380] JOURNAL DE L'ATELIER — le parfum se corrige tâche par tâche + parfums en en-tête. (1) Chaque carte du journal affiche désormais « 🎨 parfum1 · parfum2 » (parfums distincts de la session, ordre de première apparition) — une session sans parfums le dit et pointe vers 🎯/🖊. (2) Nouveau bouton « 🖊 Par tâche » : liste des tâches (durée, parfums, badge mutualisée) → éditeur à cases par tâche (parfums de la session en tête). Une liste vide détache la tâche (vaisselle → temps commun, règle v1310). Le temps par parfum se recalcule TOUT SEUL : les moteurs relisent t.parfums à chaque calcul — prouvé avant/après sur le vrai moteur (on déplace du temps, on n'en invente pas ; total identique à la milliseconde). Persistance prodSessUpsert (cache + Dexie), transitions de modal EN PLACE (règle v1375), garde anti-écrasement : le flux session (🎯) demande confirmation avant d'écraser des corrections par tâche, et le drapeau tombe s'il écrase. La garde v1357 (escJs seul chemin d'échappement) a attrapé ma première version — corrigée. Suite v1380 : 22 assertions.
// [v1379] MERINGUE COMMUNE — la base couvre enfin le total annoncé (bug attrapé par Ben, captures à l'appui). Avec Cannelle (60 mac. std) + Madeleine (17 mac. GF), l'app annonçait 239 coques std éq. mais la base commune ne couvrait que les 120 de la Cannelle (la Madeleine, sans ingrédient coque étiqueté, pesait zéro — pesée telle quelle : une demi-meringue). Modèle tranché par Ben : GF converti en équivalent-coque standard (1 GF = 3,5 std), meringue MUTUALISÉE sur le total → la base est mise à l'échelle eqTotal/eqPorteurs (×1,99 dans son cas : eau 195,64 → 389,65 g). Les ajouts propres (noisettes du Piémont…) sont rendus au parfum au lieu d'être fondus dans la base. UN moteur (_meringueCommuneCalc) alimente les 3 surfaces (aperçu formulaire, fiche de production, fiche de pesée) — l'ancien motif (aggCommun) est éradiqué. À l'écran : « dimensionnée pour N coques std éq. », ⛔ rouge si aucun parfum ne porte de base, « partage la base commune » pour un parfum sans rien en propre. Racine corrigée au passage : le normaliseur décompose les ligatures œ→oe/æ→ae (NFD ne le fait pas) — « Blancs d'œufs » redevient de la base, et « oeuf » tapé au copilote trouve « œuf ». Cas courant 2 parfums standards : facteur exactement 1, pas un gramme ne bouge. Suite v1379 : 27 assertions.
// [v1378] ATELIER — le rappel de pesée ne s'auto-ouvre plus sur les deux étapes meringue. Demande de Ben : pendant une production, la fiche de pesée (grammages) s'ouvrait au lancement de plusieurs étapes ; il veut la retirer pour « Pesée des ingrédients meringue » et « Pesée de la meringue pour division » (grammages déjà pesés → bruit), et la garder pour le tant pour tant. Nouvelle fonction pure _atRappelPesee(label) qui porte la POLITIQUE d'auto-ouverture (ne renvoie que 'tpt') ; atLaunch décide via elle. _atPeseeKind reste intact (il reconnaît toujours les pesées meringue — on coupe la décision, pas la connaissance). Le rappel de la fiche recette complète au lancement de batch (lancerBatchAvecFiche) est inchangé. Suite v1378 : 11 assertions.
// [v1377] DEVIS ↔ COMMANDE — rebascule réparée + devis périmé/régénération. BUG corrigé : cmdToDevisConfirm plantait sur `const today = today()` (le const masquait la fonction globale et l'appelait avant initialisation → ReferenceError, zone morte temporelle) ; tout rebasculement d'une commande propre (sans paiement) en devis échouait avec « Erreur pendant la transformation ». Fix : variable renommée (`const auj = today()`). NOUVEAU : un devis accepté devient « périmé » dès que la commande liée est modifiée (lignes ou montant) — saveCmd pose/lève le drapeau perimeCommande via _devisPerime (pur, money2 lisse les centimes, aucune fausse alerte). L'écran document affiche alors un bandeau « ne correspond plus à la commande » + bouton « 🔄 Régénérer depuis la commande » ; devisRegenererDepuisCommande recopie le contenu actuel de la commande dans le devis (même numéro/statut), lève le drapeau et propose l'envoi au client (Visualiser & envoyer). On ne réécrit jamais un devis accepté en douce. Suite v1377 : 22 assertions.
// [v1376] MISE EN BOÎTE — Fusion de deux boîtes du même lot. Regrouper physiquement des boîtes issues d'un même lot quand les stocks baissent, SANS perdre la traçabilité. Règle métier stricte (décision de Ben) : on ne fusionne QUE deux boîtes du même parfum ET du même lot (même etiquetteDe = même lot parent, + recipeId/composant/degDeclasse corroborants) — tout le reste est REFUSÉ avec motif (lots/parfums/stades différents, même boîte, non-boîte, boîtes vides). Préserve : somme des restes + des quantités produites/réelles (invariant produit−consommé=reste intact), DLC la plus courte (la plus prudente), traçabilité (etiquetteDe conservé + historique fusionHisto empilable + entrée d'audit dédiée « fusion-boite »). Sécurité : snapshot avant, update+delete dans une transaction. Deux modes : sélection manuelle (lots à ≥2 boîtes, coche exactement 2, même lot garanti par le groupe) et flash QR (scan des 2 boîtes, réutilise openScanner). Entrée « 🔀 Fusionner des boîtes » sur Stock par parfum. Suite v1376 : 35 assertions.
// [v1375] MISE EN BOÎTE — deux bugs d'étiquettes corrigés (audit du flux). BUG#2 (critique) : dans « Étiquettes groupées », lbGenerate lisait des champs #lbcopies_/#lbpieces_ INEXISTANTS dans le DOM (les saisies vivent dans le modèle _lbLignes) → copies forcé à 1 et pièces/boîte ignorées (repli sur la quantité du lot). Désormais lbGenerate lit _lbLignes (la source de vérité, comme le rangement) et imprime dès copies>0 : les quantités saisies sont honorées ET plusieurs boîtes par lot (3×20 + 1×12) sont enfin possibles dans le PDF. BUG#1 : depuis Stock par parfum → « Étiquettes (boîtes) », un toast s'affichait mais le menu Imprimer/Enregistrer disparaissait — closeModal() puis ré-ouverture déclenchait un history.back() dont le popstate différé refermait le modal de résultats ; _etiqValiderGo ne ferme plus le modal avant les résultats, et _etiqResultats remplace le contenu EN PLACE. Règles gravées : l'écran et le générateur lisent le même modèle (v1339/v1374) ; on ne ferme-puis-rouvre jamais un modal à travers un saut async (v1363). Suite v1375 : 17 assertions (dont preuve comportementale à DOM vide).
// [v1374] CHANTIER FIABILITÉ 3/3 — La carte des dépendances entre les chiffres. 11 figures déclarées (FIGURES) : CA encaissé, CA marchés, charges fixes, coût de revient FIFO, point mort, stock fini par parfum, prévisionnel, revenu horaire, sérénité, audits comptable et stock/temps — chacune avec ses sources (tables Dexie ET clés kv), ses amonts, sa règle gelée en une ligne, ses suites de tests. Moteur d'aval transitif (_figAval) + outil `node tests/quoi-retester.js <sources> [--run]` : « j'ai touché X, voici les chiffres périmés et les suites à relancer ». Au commit d'audit, la carte est prévenue (sources dédupliquées, kv par clé) et l'événement sm-figures-perimees est émis ; AUCUN re-rendu automatique (non-but déclaré et testé). Écran « 🕸 Carte des chiffres » dans Sauvegarde & sécurité (sources en clair, règles, protections, badge périmé). Gardes : fonctions/tables/clés kv/suites citées existent, aucun cycle (détecté et nommé), ratchet A7 sur les figures sans suite (une seule : sérénité, déclarée). Suite v1374 : 23 assertions — agrégat : 80 suites, 1779 assertions vertes.
// [v1373] CHANTIER FIABILITÉ 2/3 — Schémas de validation à l'entrée. 21 tables couvertes par un schéma (types français : nombreFini, dateJ, idRef, horoMs…) appliqué via les hooks Dexie creating/updating : une écriture PROUVABLEMENT mal formée (montant en chaîne, NaN, date malformée, tableau attendu, champ d'identité absent à la création) est REFUSÉE — exception typée ValidationRefusee, toast avec motif lisible, entrée « rejet » au journal. Le suspect non prouvé (énumération inconnue — « embarque » serait signalé aujourd'hui —, signe inhabituel) PASSE et est journalisé (« suspect ») : leçon v1370, on ne crie pas au loup sur du sain (corpus de 11 fixtures réelles en garde-fou). Les modifications ne valident que les champs écrits : les fiches anciennes restent éditables. Restauration/fusion : hooks suspendus (audit compris), une seule entrée récapitulative. Interrupteur « validation stricte » à l'écran Sauvegardes (défaut : activée ; désactivée → refus évités journalisés + bannière ambre). Corrigé au passage : Dexie.ignoreTransaction sur toutes les écritures de journal issues de hooks/rappels (zone Dexie morte). Suite v1373 : 32 assertions.
// [v1372] CHANTIER FIABILITÉ 1/3 — Stockage unifié + journal d'audit. (a) Ouverture : suite livrée ROUGE réparée (5 harnais sans _dansPeriode, 2 gardes vague 56 ré-ancrées sur le dossier de justification) + 18 suites orphelines (vagues 63-71) inscrites dans run-all.js. (b) Table Dexie `kv` (schéma v32) : 17 clés localStorage MÉTIER (modèles de pyramides, compteurs légaux de factures/avoirs, journal copilote, charges récurrentes, temps appris, motifs de suppression…) recopiées en base → sauvegardées, vérifiées par somme de contrôle, restaurées automatiquement au boot si localStorage a été purgé (purge iOS / restauration / nouvel appareil). Ordre d'écriture gelé : localStorage d'abord, kv ensuite — en divergence, localStorage gagne et la divergence est journalisée. Point de passage unique (setItem/removeItem enveloppés) : les clés futures sont couvertes d'office, et toute clé non classée fait échouer la suite. (c) Table `auditLog` : chaque création/modification/suppression en base tracée champ par champ (avant → après) via les hooks Dexie, flush au COMMIT seulement, entrées bornées 1200 car., rétention 2000, écran « Sauvegarde & sécurité → 📜 Journal des écritures ». journalCompta reste le journal légal. (d) Somme de contrôle : le périmètre voyage dans le fichier (_checksumTables) ; les sauvegardes d'avant v1372 se vérifient sur la liste héritée figée — aucune invalidation rétroactive. (e) Une restauration d'ancienne sauvegarde n'efface ni kv ni auditLog. Suite v1372 : 49 assertions, preuves par réintroduction. (Note : la v1371 d'une session interrompue — journal copilote durable — est ré-absorbée ici.)
// [v1275] Nettoyage (Sweeper) : suppression de l'écran d'accueil expérimental « Le Fil » (renderAccueil + 8 helpers + variable _accueilSlide, ~282 lignes de JS) et de ses styles CSS .acc-* (~35 lignes) dans index.html. Code entièrement dormant : débranché du routeur (accueil → renderDash inchangé), appelé nulle part, aucune dépendance externe. Aucun changement fonctionnel ni visuel. Suite de tests (282 assertions) verte après coupe.
// [v1274] Espace CGV : les Conditions Générales de Vente et de Prestation (version 3, conformes à l'audit juridique) sont intégrées comme une nouvelle rubrique du menu. Le texte des 16 articles + l'annexe (formulaire de rétractation) est figé ; seuls les champs variables (identité, SIRET, adresse, contact, médiateur MCP pré-rempli) sont renseignés via un formulaire, persistés dans sm_settings.legal (donc inclus dans les sauvegardes). Diffusion en Page CGV affichable + Export PDF (impression → Enregistrer en PDF), bloquée tant qu'un champ obligatoire manque. Aucune table Dexie ajoutée, aucune fonctionnalité retirée.
// [v1273] Commandes : les commandes des SEMAINES FUTURES sont désormais compilées dans un encart « À venir » (déplié par défaut, une ligne par commande comme « À encaisser »), groupé par semaine (de la plus proche à la plus lointaine, dates croissantes). Seules les commandes de la SEMAINE COURANTE (+ retards non livrés) restent en cartes complètes dépliées → lisibilité accrue. Bascule automatique : dès que la semaine d'une commande arrive, elle repasse en carte complète. Aucune logique de statut/paiement/produisibilité modifiée.
// [v1272] Temps de production : le tableau « Par parfum / recette » (qui débordait à droite sur iPhone) est remplacé par un rendu en CARTES. Une carte par parfum : nom + nb de batches en tête, puis Réel / Actif / Moy./batch en grille 3 colonnes. Aucune donnée ni logique changée (garde-fou actif>réel + ⚠ conservés). Tableaux « Par jour » et « Détail par batch » inchangés.
// [v1271] Assemblage : le bouton « Assembler » ne démarre plus de session/chrono d'atelier (l'assemblage physique est fait en amont, temps déjà compté). Il matérialise seulement l'action (décrément composants + création lot).
// [v1270] Section Impot sur le revenu dans la Comptabilite : abattement micro (71%/50%) + taux marginal (30% par defaut) -> impot estime et net reel apres URSSAF+impot. Taux reglable dans Parametres.
const CACHE = 'sm-iphone-v505';
const ASSETS = [
  './',
  './index.html',
  './app.js',
  './dexie.min.js',
  './qr.min.js',
  './rd_packs.json',
  './rd_pack_alice.json',
  './rd_pack_bau.json',
  './rd_pack_lenotre.json',
  './rd_pack_karina.json',
  './rd_pack_maddie.json',
  './rd_pack_sab.json',
  './rd_pack_tfp.json',
  './rd_pack_quinonero.json',
  './rd_pack_chiara.json',
  './rd_pack_matt.json',
  './rd_pack_maja.json',
  './rd_pack_herme.json',
  './rd_pack_michalak.json',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './Outfit-Regular.ttf',
  './Outfit-SemiBold.ttf',
  './Outfit-Bold.ttf',
  './BellotaText-Regular.ttf',
  './BellotaText-Bold.ttf'
];

// INSTALL : précache + activation IMMÉDIATE de la nouvelle version (skipWaiting).
// On n'attend plus un clic utilisateur : la mise à jour s'applique d'elle-même.
self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

// ACTIVATE : purge des anciens caches puis prise de contrôle des onglets.
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Permet à l'application de demander l'activation immédiate de la version en attente
// (déclenché par le bouton « Recharger l'application »).
self.addEventListener('message', e => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});

// FETCH :
// - Pour le CODE (index.html, app.js, et la navigation) : NETWORK-FIRST.
//   On tente d'abord le réseau (donc la dernière version en ligne) ; en cas d'échec
//   (hors-ligne), on retombe sur le cache. Fini les vieux app.js servis indéfiniment.
// - Pour le RESTE (librairies, icônes) : Stale-While-Revalidate (rapide + hors-ligne).
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  let url;
  try { url = new URL(req.url); } catch (err) { return; }
  if (url.origin !== self.location.origin) return;

  const isCode = req.mode === 'navigate'
    || url.pathname.endsWith('/app.js')
    || url.pathname.endsWith('/index.html')
    || url.pathname === '/' || url.pathname.endsWith('/');

  if (isCode) {
    // network-first
    e.respondWith(
      fetch(req).then(res => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return res;
      }).catch(() => caches.open(CACHE).then(c => c.match(req).then(r => r || c.match('./index.html'))))
    );
    return;
  }

  // stale-while-revalidate pour le reste
  e.respondWith(
    caches.open(CACHE).then(cache =>
      cache.match(req).then(cached => {
        const network = fetch(req).then(res => {
          if (res && res.status === 200 && res.type === 'basic') {
            cache.put(req, res.clone());
          }
          return res;
        }).catch(() => cached);
        return cached || network;
      })
    )
  );
});
